 name: action

 on:
   workflow_dispatch:
   schedule:
     - cron: '*/10 * * * *'
   watch:
     types: started
   repository_dispatch:
     types: _

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
       - name: Checkout
         run: |
           git clone https://github.com/tsuyoshi727/action-group.git ~/action-group
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           cd ~/action-group
           npm install
      - name: '运行 【百度极速版】'
        run: |
          cd ~/action-group
          node Task/baidu_speed.js
      - name: '运行 【百度极速版】'
        run: |
          cd ~/action-group
          node Task/baidu_cash.js
       - name: '运行 【多看点】'
         run: |
           cd ~/action-group
           node Node/dkd.js
         env:
           BAIDU_TASK: ${{ secrets.BAIDU_TASK }}
           BAIDU_CASH: ${{ secrets.BAIDU_CASH }}
           DKDURL: ${{ secrets.DKDURL }}
           DKDHD: ${{ secrets.DKDHD }}
           DKDBODY: ${{ secrets.DKDBODY }}
           DKDTXURL: ${{ secrets.DKDTXURL }}
           DKDTXHD: ${{ secrets.DKDTXHD }}
           DKDTXBODY: ${{ secrets.DKDTXBODY }}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
