name: 'deploy for tencentyun'

on:
  workflow_dispatch:
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2

    - name: 安装依赖模块(aiohttp)
      run: |
        sudo -H pip3 install --upgrade pip
        sudo -H pip3 install setuptools
        mkdir other_models
        sudo -H pip3 install -r requirements.txt -t ./other_models
    - name: 安装ServerlessFramework
      run: sudo npm install -g serverless

    - name: 重构文件目录结构并部署至腾讯云 #将云函数相关文件全移动到./serverless,并以此为根目录上传部署到SCF
      run: |
        if [ -z "$TENCENT_SECRET_ID" ]; then
        echo "部署至腾讯云需要填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY两个secrets"
        exit -1
        fi
        sudo mv BiliExp.py ./serverless
        sudo mv ./tasks ./serverless
        sudo mv ./BiliClient ./serverless
        sudo mv ./other_models/* ./serverless
        sudo mkdir ./serverless/config
        sudo mv ./config/*.json ./serverless/config
        cd ./serverless
        sudo rm -f aliyun_serverless.yml
        sls deploy --debug
      env:
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          TIMEOUT: 120
