
name: 腾讯云函数

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: scf

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: "安装依赖和serverless工具"
        run: |
          pip install -r requirements.txt -t .

      - name: "替换文件"
        run: |
          wget -O index.py https://raw.githubusercontent.com/Zero-S1/xmly_speed/master/index.py
          wget -O .gitignore https://raw.githubusercontent.com/Zero-S1/xmly_speed/master/.gitignore
          wget -O .gitignore https://raw.githubusercontent.com/Zero-S1/xmly_speed/master/xmly_speed.py

      - name: "部署到腾讯云函数"
        run: |
        env:
          STAGE: dev
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
