 name: 腾讯自选股

 on:
   workflow_dispatch:
   schedule:
     - cron: '0 */2 * * *'
   watch:
     types: started
   repository_dispatch:
     types: _

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     env:
         TX_USERHEADER: ${{ secrets.TX_USERHEADER }}
         TX_USERKEY: ${{ secrets.TX_USERKEY }}
         TX_CASHHEADER: ${{ secrets.TX_CASHHEADER }}
         TX_SIGNHEADER: ${{ secrets.TX_SIGNHEADER }}
         TX_SIGNKEY: ${{ secrets.TX_SIGNKEY }}
         TX_TASKHEADER: ${{ secrets.TX_TASKHEADER }}        
         TX_TASKKEY: ${{ secrets.TX_TASKKEY }}
         TX_WXTASKKEY: ${{ secrets.TX_WXTASKKEY }}
         TX_COWKEY: ${{ secrets.TX_COWKEY }}
         TZ: Asia/shanghai
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           npm install
       - name: '运行 【腾讯自选股】'
         run: |
           node txstock.js
         env:
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
