# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * * '
  watch:
    types: [started]
  repository_dispatch:
    types: xmly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Zero-S1/xmly_speed ~/xmly_speed
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: |
          cd ~/xmly_speed
          pip install -r ./requirements.txt 
      - name: '运行 【喜马拉雅极速版】' 
        run: |
          cd ~/xmly_speed
          python3 xmly_speed.py 
        env:
          XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}
        # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }}
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
          TG_USER_ID:  ${{secrets.TG_USER_ID}}
