name: 喜马拉雅极速版

on:
  schedule:
    - cron: '*/5 * * * * '
  watch:
    types: [started]
  repository_dispatch:
    types: xmly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Zero-S1/xmly_speed.git ~/xmly_speed
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: |
          cd ~/xmly_speed
          pip install -r ./requirements.txt 
      - name: 'run 喜马拉雅极速版' 
        run: |
          ~/xmly_speed
          python3 xmly_speed.py 
        env:
            XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}
          # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }}
            TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID:  ${{secrets.TG_USER_ID}}
