 name: 笑谱

 on:
   workflow_dispatch:
   schedule:
     - cron: '0 */1 * * *'
   watch:
     types: started
   repository_dispatch:
     types: xp

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
       - name: Checkout
         run: |
          git clone https://github.com/ZhiYi-N/script ~/script
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           cd ~/script
           npm install
       - name: '运行 【笑谱】'
         run: |
           cd ~/script
           node xp.js
         env:
           VIDEOHEADER: ${{ secrets.VIDEOHEADER }}
           VIDEOBODY: ${{ secrets.VIDEOBODY }}
           GOLDBODY: ${{ secrets.GOLDBODY}}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
