name: 笑谱

 on:
   workflow_dispatch:
   schedule:
     - cron: '*/5 * * * *'
   watch:
     types: started
   repository_dispatch:
     types: xp

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
       - name: Checkout
         run: |
          git clone https://github.com/ZhiYi-N/script ~/script
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           cd ~/script
           npm install
       - name: '运行 【笑谱】'
         run: |
           cd ~/script
           node xp.js
         env:
           VIDEOHEADER: {"Connection":"keep-alive","Accept-Encoding":"gzip, deflate, br","version":"1.4.4","mchtNo":"100529600058887","Content-Type":"application/json; charset=utf-8","source":"VEISHOP_APP_IOS","shopkeeperId":"1148855820752977920","User-Agent":"VeiShop, 1.4.4 (iOS, 14.3, zh_CN, Apple, iPhone, 1CC223A6-BB53-47A6-9091-AF666380AF50)","token":"477d38c1aeea438cb4bad3c7291bcc01","X-User-Agent":"VeiShop, 1.4.4 (iOS, 14.3, zh_CN, Apple, iPhone, 1CC223A6-BB53-47A6-9091-AF666380AF50)","traceid":"31348789869336780800161171877931300002bfa26fc","Host":"veishop.iboxpay.com","Accept-Language":"zh-Hans;q=1","Accept":"*/*","Content-Length":"753"}
           VIDEOBODY: {"type":1,"videoList":[{"videoId":"1352316226536230912","type":1,"isFinishWatch":false},{"videoId":"1347604383523684352","type":1,"isFinishWatch":false},{"videoId":"1351234317852889088","type":1,"isFinishWatch":false},{"videoId":"1351953800397606912","type":1,"isFinishWatch":false},{"videoId":"1350504033662554112","type":1,"isFinishWatch":false},{"videoId":"1353039948712812544","type":1,"isFinishWatch":false}],"actId":"284"}
           GOLDBODY: {"type":2,"videoList":[{"videoId":"1353039948712812544","type":1,"isFinishWatch":false},{"videoId":"1350145799143575552","type":1,"isFinishWatch":false},{"videoId":"1346518696607178752","type":1,"isFinishWatch":false},{"videoId":"1350506624530272256","type":1,"isFinishWatch":false},{"videoId":"1352316312976642048","type":1,"isFinishWatch":false},{"videoId":"1353043918864818176","type":1,"isFinishWatch":false},{"videoId":"1351591074517241856","type":1,"isFinishWatch":false},{"videoId":"1349419671927930880","type":1,"isFinishWatch":false},{"videoId":"1346767214588551168","type":1,"isFinishWatch":false},{"videoId":"1349350487973969920","type":1,"isFinishWatch":false},{"videoId":"1349410892956057600","type":1,"isFinishWatch":false}],"actId":"284"}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
