 name: 笑谱直播

 on:
   workflow_dispatch:
   schedule:
     - cron: '*/5 8-23 * * *'
   watch:
     types: started
   repository_dispatch:
     types: xpzb

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     env:
         XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER }}
         XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
         XP_live: ${{ secrets.XP_live }}
         XP_CASH: ${{ secrets.XP_CASH }}
     steps:
       - name: Checkout
         run: |
          git clone https://github.com/ziye12/JavaScript ~/JavaScript
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         run: |
           cd ~/JavaScript
           npm install
       - name: '运行 【笑谱直播】'
         run: |
           cd ~/JavaScript
           node Task/iboxpayZB.js
         env:
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
